# Generated by Django 3.2.1 on 2024-05-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
    ]
